<?php


namespace app\controllers\admin;

use Yii;
use yii\web\Controller;
use app\models\User;

class AdminController extends Controller
{
    public $layout = 'admin/main';

    public function beforeAction($action)
    {
        //check user rights
        $user = Yii::$app->user;

        if ($user->isGuest){
            return $this->goHome();
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}